export const apiRoutes = {
  getTokenByPassword: `/login`,
  getTokenByRefresh: `/refresh_token`,
  getProfile: `/getProfile`,
  user: `/users/:id?`,
  getRolesList: `/roles`,
  getOperationList: `/status_operations`,
  getPlcIndication: `/plc/indication`,
  getDBIndication: `/actuator/health/db`,
  addressPlc: `/plc/address/:id?`,
  reference: `/references/:id?`,
  recipe: `/recipe/:id?`,
  recipeGraph: `/recipe_graph/:id?`,
  referenceListName: `/references/list`,
  operation: `/operations/:id?`,
  part: `/parts/:id?`,
  graphResultReal: `/graph_results_real`,
  graphResultBoolean: `/graph_results_boolean`,
  getTypeOpc: `/typesOpc`,
  getUnit: `/units`,
  tagResults: `/tags_result/:id?`,
  operationResults: `/operation_result/:id?`,
  downloadOperationsCsv: `/download_operations_csv`,
  downloadPartsCsv: `/download_parts_csv`,
  graphResultEffort: `/graph_results_effort`,
  graphResultMoment: `/graph_results_moment`,
};

export const pageRoutes = {
  main: '/',
  auth: '/auth',
  user: '/user',
  appointment: '/appointment/:id',
};
